version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    build: .
    image: triton-benchmark
    command: make worker
    volumes:
      - .:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0

  triton:
    image: nvcr.io/nvidia/tritonserver:22.02-py3
    ports:
      - 9000:8000
      - 9001:8001
      - 9002:8002
    command: tritonserver --model-repository=/models
    volumes:
      - ./model_repository:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  api:
    build: .
    image: triton-benchmark
    ports:
      - 8000:8000
    command: make api
    volumes:
      - .:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0

  dashboard:
    build: .
    image: triton-benchmark
    ports:
      - 5555:5555
    command: make dashboard
    volumes:
      - .:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0
